name: dart_garage
version: 0.0.1
dependencies:
  angular: ">=0.12.0 <0.13.0"
  di: ">=0.0.39 <0.1.0"
  browser: any
  js: any
  shadow_dom: any
  observe: any
  polymer: any
dev_dependencies:
  unittest: any
transformers:
- angular
- di